### ISSUE TITLE
Can we delete tag v3.0.0.70400-alpha9

### ISSUE THREAD

**Issue by midahp** [maintaina-com/Injector#6]
I don't know if this was created intentionally or not, but now this tag is considered 'newer' than all the other tags.
So an composer update will always update to that version instead for example to `v3.0.0alpha10` which is newer.

We could either delete that tag or create a new version with a higher version number (i.e. v3.0.1).
@ralflang what do you suggest we do here?

**Comment by ralflang** [comment]
That's not as intended. Best delete the offending tag until we have a better solution.

**Comment by midahp** [comment]
Ok I deleted the tag.  and ran the Update Satis workflow. The tag is now gone in horde-satis.maintaina.com and composer update behaves as expected
